name: main
on:
  push:
    branches: [master]
  schedule:
  - cron: '0 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install pre-commit-mirror-maker
    - run: git config --global user.name Pedro Algarvio
    - run: git config --global user.email pedro@algarvio.me
    - run: pre-commit-mirror . --language=python --package-name=nox --types=file
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/master --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
